- name: Add k8s CA certificate (1/3)
  ansible.builtin.file: 
    path: /usr/local/share/ca-certificates/kubernetes
    state: directory

- name: Add k8s CA certificate (2/3)
  ansible.builtin.file:
    src: /etc/kubernetes/pki/ca.crt
    dest: /usr/local/share/ca-certificates/kubernetes/ca.crt
    state: link

- name: Add k8s CA certificate (3/3)
  shell: update-ca-certificates

- name: Load k8s CA certificate in docker
  shell: systemctl restart docker