---
- name: Stop running onos instance
  become: yes
  community.docker.docker_container:
    name: onos
    state: absent
- name: ONOS docker
  docker_container:
    name: onos
    image: '{{ onos.image }}'
    ports:
      - "830:830"
      - "5005:5005"
      - "8101:8101"
      - "8181:8181"