---
- name: Copy Kube config
  ansible.builtin.copy:
    src: '{{ kube_config_local_path }}'
    dest: .kube/config

- name: Join k8s cluster
  shell: |
    kubeadm join --token {{ token }} \
                  --discovery-token-unsafe-skip-ca-verification \
                {{ master }}:6443