- name: Create certificate directory
  ansible.builtin.file:
    path: '{{ certificate_path }}'
    state: directory

- name: Configuring v3 extension
  ansible.builtin.template:
    src: v3.ext.j2
    dest: '{{ certificate_path }}/{{ certificate.common_name }}.v3.ext'

- name: Generate an OpenSSL private key
  community.crypto.openssl_privatekey:
    path: '{{ certificate_path }}/{{ certificate.common_name }}.pem'
    type: RSA
    size: 4096

- name: Generate an OpenSSL Certificate Signing Request
  community.crypto.openssl_csr:
    path: '{{ certificate_path }}/{{ certificate.common_name }}.csr'
    privatekey_path: '{{ certificate_path }}/{{ certificate.common_name }}.pem'
    common_name: '{{ certificate.common_name }}'
    subject_alt_name: "{{ item.value | map('regex_replace', '^', 'DNS:') | list }}"
  with_dict:
    dns_server: '{{ certificate.subjectAltName }}'

- name: Generate an OpenSSL certificate signed with the CA certificate
  shell: openssl x509 -req -days 365 -in {{ certificate.common_name}}.csr -CA {{ certificate.ca_path }} -CAkey {{ certificate.ca_privatekey_path }} -CAcreateserial  -out {{ certificate.common_name}}.crt -extfile {{ certificate.common_name }}.v3.ext
  args:
    chdir: '{{ certificate_path }}'