---
- name: Stop running stratum instance
  become: yes
  community.docker.docker_container:
    name: stratum-container
    state: absent
- name: change docker sock permissions
  become: yes
  ansible.builtin.file:
    path: /var/run/docker.sock
    mode: '0666'
- block:
  - name: starting the stratum container
    shell: "~/stratum/setup_dev_env.sh -- --privileged -d --network=host --name stratum-container"
  - name: Check if stratum already been built
    stat:
      path: ~/stratum/stratum_bmv2_deb.deb
    register: stat_result
  - name: Build stratum
    import_tasks: 'bmv2_stratum_build.yaml'
    when: not stat_result.stat.exists
  - name: apt-update
    shell: "docker exec stratum-container sudo apt-get update"
  - name: installing stratum
    shell: "docker exec stratum-container sudo apt-get install -y --reinstall /stratum/stratum_bmv2_deb.deb"
  - name: copying chassis config
    shell: "docker cp /tmp/chassis_config.pb.txt stratum-container:/chassis_config.pb.txt"
  - name: strating stratum with the chassis
    shell: "docker exec -d stratum-container sudo stratum_bmv2 -chassis_config_file=/chassis_config.pb.txt"
  become: yes
  become_user: '{{ stratum.bmv2_user }}'
