---
- block:
  - name: Remove unstable ONL APT repo
    ansible.builtin.file:
      path: /etc/apt/sources.list.d/multistrap-onl.list
      state: absent
    tags: never

  - name: Install dependencies (system)
    ansible.builtin.apt:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
      autoclean: yes
      update_cache: true
    with_items: "{{ lookup('vars', (ansible_distribution | lower)+ '_dependencies')}}"
    tags: never

  - name: Install dependencies (Python)
    ansible.builtin.pip:
      name: "{{ item.name }}=={{ item.version }}"
    with_items: "{{ python_packages }}"
    tags: never

  - name: Setting hugepages
    ansible.posix.sysctl:
      name: vm.nr_hugepages
      value: "128"
      state: present

  - name: Mount hugepage
    ansible.posix.mount:
      name: /mnt/huge
      src: nodev
      fstype: hugetlbfs
      opts: "pagesize=1GB"
      state: mounted
    when: ansible_distribution == 'Debian'

  - name: Disable swap
    shell: swapoff -a

  become: yes
